const CRONO = [
  { id: "1.1", actividad: "Generación de proceso de cambio de semestre en SRH producción (plazas asignatura).", 
    proceso: "", responsable: "SAF", marzo: "2-12", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "1.2", actividad: "Notifica el banco de horas disponible a la Secretaría Académica.", 
    proceso: "", responsable: "SAF", marzo: "2-12", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "1.3", actividad: "La DGRF realiza la actualización del banco de horas.", 
    proceso: "Control Presupuestal y Laboral de la PA", responsable: "SAF", marzo: "2-12", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "2", actividad: "Capacitación a Secretarios de Facultad y responsables de programación académica", 
    proceso: "", responsable: "DGAE / DGAA / SAF", marzo: "2-13", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "3", actividad: "Envío de observaciones y solicitudes de requerimientos adicionales del banco de horas con la justificación correspondiente (proyecciones académicas)", 
    proceso: "", responsable: "DGAA / DGRI /DAFBG", marzo: "23-25", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "4", actividad: "Liberación de la programación académica homóloga anterior para su actualización.", 
    proceso: "Rolado", responsable: "DGAE", marzo: "13 y 17", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "5", actividad: "Segunda sesión de tutoría, ejercicio en el Sistema PLANEA (SIP).", 
    proceso: "https://planea.uv.mx/trayectorias", responsable: "DGDAIE / EA", marzo: "7-14", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "6", actividad: "Análisis de la información generada en el ejercicio PLANEA.", 
    proceso: "", responsable: "DGDAIE / EA", marzo: "17-19", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "7", actividad: "Mantenimiento y envío de la programación académica (titulares y vacantes, considerando que las Experiencias Educativas (EE) de Servicio Social, Experiencia Recepcional y experiencias prácticas no están sujetas a convocatoria).", 
    proceso: "MPA", responsable: "EA", marzo: "20", abril: "9", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "8.1", actividad: "Enviar a las Áreas Académicas las solicitudes de descarga académica con la validación del CT.", 
    proceso: "Oficio-Dictamen del CT", responsable: "EA", marzo: "20", abril: "9", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "8.2", actividad: "Difusión de las EE vacantes a las Direcciones Generales de Áreas Académicas DGAA, Dirección General de Investigaciones (DGI), Dirección General de Difusión Cultural (DGDC) y Dirección General de la Unidad de Estudios de Posgrado (DGUEP), para efecto de reubicación, complementos de carga de investigadores, ejecutantes y técnicos académicos.", 
    proceso: "MPA", responsable: "EA", marzo: "20", abril: "9", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "8.3", actividad: "Reportar a las DGAA sobre las acciones realizadas para la reubicación de académicos con Horas de Asignatura (HA), como fuente se utilizará el periodo agosto 2025-enero 2026.", 
    proceso: "MPA (académicos con HA)", responsable: "EA", marzo: "20", abril: "9", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "9", actividad: "Dictaminación de las DGAA/DGUEP/DAFBG/DGRI de la Oferta Académica cumpliendo la normatividad aplicable.", 
    proceso: "MPA", responsable: "DGRH / DGRF / DGAA / DGUEP/DAFBG/DGRI", marzo: "20", abril: "17", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "10", actividad: "Fecha límite para enviar a la  Secretaría Académica listado de PE que van a convocar EE vacantes.", 
    proceso: "", responsable: "DGRH / DGRF / DGAA / DGUEP/DAFBG/DGRI", marzo: "", abril: "22", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "11", actividad: "Dictaminación de la DGRF la disponibilidad presupuestal cumpliendo la normatividad aplicable. Programas Educativos sin EE a convocar.", 
    proceso: "", responsable: "DGRH / DGRF / DGAA / DGUEP/DAFBG/DGRI", marzo: "20", abril: "27", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "12", actividad: "Dictaminación de la DGRH la situación laboral cumpliendo la normatividad aplicable. Programas Educativos sin EE a convocar.", 
    proceso: "", responsable: "DGRH / DGRF / DGAA / DGUEP/DAFBG/DGRI", marzo: "20", abril: " ", mayo: "11", junio: "", julio: "", agosto: "" },
  { id: "13", actividad: "Recepción de solicitudes de año sabático.", 
    proceso: "SIIU", responsable: "DGAA / DGUEP /DGI / DGRI", marzo: "2", abril: " ", mayo: "4", junio: "", julio: "", agosto: "" },
  { id: "14", actividad: "Validación laboral y presupuestal de año sabático.", 
    proceso: "", responsable: "DGRH / DGRF", marzo: "", abril: "", mayo: "11-22", junio: "", julio: "", agosto: "" },
  { id: "15", actividad: "Entrega de resultados de solicitudes de año sabático al Sindicato Estatal de Personal Académico de la Universidad Veracruzana (FESAPAUV).", 
    proceso: "SIIU", responsable: "DGAA / DGUEP / DGRI / DGI", marzo: "", abril: "", mayo: "", junio: "15", julio: "", agosto: "" },
  { id: "16", actividad: "Impresión de reporte de carga académica por docente, recabar firma y envío a DGAA que corresponda.", 
    proceso: "", responsable: "EA / DGUEP", marzo: "", abril: "", mayo: "4-25", junio: "", julio: "", agosto: "" },
  { id: "17", actividad: "Generación de formatos de Complemento de Carga y Carga Obligatoria, atendiendo lo establecido en la normatividad aplicable, se envía por Hermes a DGRH.", 
    proceso: "", responsable: "EA / DGUEP", marzo: "", abril: "", mayo: "4-25", junio: "", julio: "", agosto: "" },
  { id: "18", actividad: "Envío de formatos de descarga y/o comisiones académicas o institucionales a la DGRH.", 
    proceso: "", responsable: "DGAA / DGUEP / DGRI / DGI / DGRH", marzo: "", abril: "6", mayo: "25", junio: "", julio: "", agosto: "" },
  { id: "19", actividad: "Emisión y validación de EE para convocar.", 
    proceso: "", responsable: "DGAA / DGUEP / DGRI / DGI / DGRH", marzo: "", abril: "", mayo: "14-20", junio: "", julio: "", agosto: "" },
  { id: "20", actividad: "Publicación de Convocatoria de EE por Programa Educativo con oferta autorizada.", 
    proceso: "SYRCONI - SYRCONV - SYRCONB", responsable: "DGAA / DGUEP / DGRI / DGI / DGRH", marzo: "", abril: "", mayo: "27", junio: "", julio: "", agosto: "" },
  { id: "21", actividad: "Tercera sesión de tutorías (orientación para la IL).", 
    proceso: "", responsable: "DGDAIE / EA", marzo: "", abril: "", mayo: "16-23", junio: "", julio: "", agosto: "" },
  { id: "22", actividad: "Preparación de la inscripción en línea.", 
    proceso: "", responsable: "DGAE / SIIU / EA", marzo: "", abril: "", mayo: "12-29", junio: "", julio: "", agosto: "" },
  { id: "23", actividad: "Inscripción en línea por los estudiantes.", 
    proceso: "", responsable: "DGAE / SIIU / EA", marzo: "", abril: "", mayo: "", junio: "1-3", julio: "", agosto: "" },
  { id: "24", actividad: "Análisis de cierres y aperturas con calificaciones de ordinarios.", 
    proceso: "", responsable: "DGAE / SIIU / EA", marzo: "", abril: "", mayo: "", junio: "30", julio: "6", agosto: "" },
  { id: "25", actividad: "Notificación a la SA del listado de plazas vacantes de tiempo completo y medio tiempo con disponibilidad presupuestal.", 
    proceso: "", responsable: "SAF", marzo: "", abril: "", mayo: "", junio: "", julio: "3-9", agosto: "" },
  { id: "26", actividad: "Solicitud de ocupación temporal de plazas vacantes de tiempo completo y medio tiempo a la Secretaría de Administración y Finanzas.", 
    proceso: "", responsable: "DGAA / DGUEP / DGRI / DGI / DGDC / DAFBG", marzo: "", abril: "", mayo: "", junio: "25", julio: "3", agosto: "" },
  { id: "27", actividad: "Generar el reporte de cargas académicas por organización para el proceso de revisión de cargas académicas a partir de que se autoriza el PE.", 
    proceso: "", responsable: "EA / DGAA / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "28", actividad: "Fecha límite de licencias con goce y sin goce de sueldo.", 
    proceso: "", responsable: "DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "9", agosto: "" },
  { id: "29", actividad: "Proceso de revisión de cargas académicas.", 
    proceso: "", responsable: "DGRH", marzo: "", abril: "", mayo: "11-27", junio: "", julio: "", agosto: "" },
  { id: "30", actividad: "Publicación de resultados de la Convocatoria de EE vacantes (subir las publicaciones de resultados en el portal institucional de las entidades convocadas). SEA y Escolarizado", 
    proceso: "", responsable: "EA / DGAA ", marzo: "", abril: "", mayo: "", junio: "", julio: "6", agosto: "" },
  { id: "31", actividad: "Bajas en ventanilla de EE.", 
    proceso: "", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "17-21" },
  { id: "32", actividad: "Análisis de cierres con calificaciones y bajas.", 
    proceso: "Movimientos de altas y bajas", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "24-25" },
  { id: "33", actividad: "Autorización de las DGAA el cierre de EE.", 
    proceso: "", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "24-25" },
  { id: "34", actividad: "La DGRF asigna o configura en subsistema la apertura de EE.", 
    proceso: "", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "24-25" },
  { id: "35", actividad: "Actualización de la carga académica con la apertura y cierre de EE.", 
    proceso: "", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "24-28" },
  { id: "36", actividad: "Inscripción a EE con lugares disponibles.", 
    proceso: "", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "26-28" },
  { id: "37", actividad: "Inscripción Posgrado.", 
    proceso: "", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "3-7 y 10-14" },
  { id: "38", actividad: "Envío de solicitudes de contratación de personal de las EE convocadas sin inconformidad o, en su caso, al siguiente día hábil de haberse resuelto la inconformidad (con los documentos de resolución) y de acuerdo al calendario de recepción de documentos para el trámite de pago de la Dirección de Personal 2026.", 
    proceso: "", responsable: "DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "3-14" },
  { id: "39", actividad: "Fecha límite de envío de la Oferta impartida en el periodo Intersemestral de Verano 2025.", 
    proceso: "Formato", responsable: "DGRH / EA / DGAA", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "28" },
  { id: "40", actividad: "Inicio de publicación de avisos de EE vacantes para personal académico interino.", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "22", julio: "", agosto: "" },
  { id: "41", actividad: "Inicio de clases Licenciatura/Posgrado.", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "17" },
  { id: "42", actividad: "Inicio de clases Sistema de Enseñanza Abierta (SEA).", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "22" },
  { id: "43", actividad: "Contratación del personal académico de EE convocadas (Escolarizado/SEA).", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "17 y 22" },
  { id: "44", actividad: "Envío de solicitudes de contratación de personal de las EE asigadas por CT al subsistema de RH.", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "15", julio: " ", agosto: "30" },
  { id: "45", actividad: "Contratación de personal no docente, a partir del inicio de labores (a solicitud de las necesidades de la entidad académica).", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "46", actividad: "Registrar y documentar los horarios de la plantilla del Personal Académico docente y no docente.", 
    proceso: "", responsable: "EA / DGUEP / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "21" }
];