const CRONO = [
  { id: "1.1", actividad: "Generación de proceso de cambio de semestre en SRH producción (plazas asignatura).", 
    proceso: "", responsable: "SAF", marzo: "2-12", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "1.2", actividad: "Notifica el banco de horas disponible a la Secretaría Académica.", 
    proceso: "", responsable: "SAF", marzo: "2-12", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "1.3", actividad: "La DGRF realiza la actualización del banco de horas.", 
    proceso: "Control Presupuestal y Laboral de la PA", responsable: "SAF", marzo: "2-12", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "2", actividad: "Capacitación a Secretarios de Facultad y responsables de programación académica", 
    proceso: "", responsable: "DGAE / DGAA / SAF", marzo: "2-13", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "3", actividad: "Envío de observaciones y solicitudes de requerimientos adicionales del banco de horas con la justificación correspondiente (proyecciones académicas)", 
    proceso: "", responsable: "DGAA / DGRI /DAFBG", marzo: "23-25", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "4", actividad: "Liberación de la programación académica homóloga anterior para su actualización.", 
    proceso: "Rolado", responsable: "DGAE", marzo: "13 y 17", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "5", actividad: "Segunda sesión de tutoría, ejercicio en el Sistema PLANEA (SIP).", 
    proceso: "https://planea.uv.mx/trayectorias", responsable: "DGDAIE / EA", marzo: "7-14", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "6", actividad: "Análisis de la información generada en el ejercicio PLANEA.", 
    proceso: "", responsable: "DGDAIE / EA", marzo: "17-19", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "7", actividad: "Mantenimiento y envío de la programación académica (titulares y vacantes, considerando que las Experiencias Educativas (EE) de Servicio Social, Experiencia Recepcional y experiencias prácticas no están sujetas a convocatoria).", 
    proceso: "MPA", responsable: "EA", marzo: "20", abril: "9", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "8.1", actividad: "Enviar a las Áreas Académicas las solicitudes de descarga académica con la validación del CT.", 
    proceso: "Oficio-Dictamen del CT", responsable: "EA", marzo: "20", abril: "9", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "8.2", actividad: "Difusión de las EE vacantes a las Direcciones Generales de Áreas Académicas DGAA, Dirección General de Investigaciones (DGI), Dirección General de Difusión Cultural (DGDC) y Dirección General de la Unidad de Estudios de Posgrado (DGUEP), para efecto de reubicación, complementos de carga de investigadores, ejecutantes y técnicos académicos.", 
    proceso: "MPA", responsable: "EA", marzo: "20", abril: "9", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "8.3", actividad: "Reportar a las DGAA sobre las acciones realizadas para la reubicación de académicos con Horas de Asignatura (HA), como fuente se utilizará el periodo agosto 2025-enero 2026.", 
    proceso: "MPA (académicos con HA)", responsable: "EA", marzo: "20", abril: "9", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "9", actividad: "Dictaminación de las DGAA/DGUEP/DAFBG/DGRI de la Oferta Académica cumpliendo la normatividad aplicable.", 
    proceso: "MPA", responsable: "DGRH / DGRF / DGAA / DGUEP/DAFBG/DGRI", marzo: "20", abril: "17", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "10", actividad: "Fecha límite para enviar a la  Secretaría Académica listado de PE que van a convocar EE vacantes.", 
    proceso: "", responsable: "DGRH / DGRF / DGAA / DGUEP/DAFBG/DGRI", marzo: "", abril: "22", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "11", actividad: "Dictaminación de la DGRF la disponibilidad presupuestal cumpliendo la normatividad aplicable. Programas Educativos sin EE a convocar.", 
    proceso: "MPA", responsable: "DGRH / DGRF / DGAA / DGUEP/DAFBG/DGRI", marzo: "20", abril: "27", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "12", actividad: "Dictaminación de la DGRH la situación laboral cumpliendo la normatividad aplicable. Programas Educativos sin EE a convocar.", 
    proceso: "MPA", responsable: "DGRH / DGRF / DGAA / DGUEP/DAFBG/DGRI", marzo: "20", abril: " ", mayo: "11", junio: "", julio: "", agosto: "" },
  { id: "13", actividad: "Recepción de solicitudes de año sabático.", 
    proceso: "Formato y anexos", responsable: "DGAA / DGUEP /DGI / DGRI", marzo: "2", abril: " ", mayo: "4", junio: "", julio: "", agosto: "" },
  { id: "14", actividad: "Validación laboral y presupuestal de año sabático.", 
    proceso: "Formato y anexos", responsable: "DGRH / DGRF", marzo: "", abril: "", mayo: "11-22", junio: "", julio: "", agosto: "" },
  { id: "15", actividad: "Entrega de resultados de solicitudes de año sabático al Sindicato Estatal de Personal Académico de la Universidad Veracruzana (FESAPAUV).", 
    proceso: "Reporte", responsable: "DGAA / DGUEP / DGRI / DGI", marzo: "", abril: "", mayo: "", junio: "15", julio: "", agosto: "" },
  { id: "16", actividad: "Impresión de reporte de carga académica por docente, recabar firma y envío a DGAA que corresponda.", 
    proceso: "MPA", responsable: "EA / DGUEP", marzo: "", abril: "", mayo: "4-25", junio: "", julio: "", agosto: "" },
  { id: "17", actividad: "Generación de formatos de Complemento de Carga y Carga Obligatoria, atendiendo lo establecido en la normatividad aplicable, se envía por Hermes a DGRH.", 
    proceso: "MPA", responsable: "EA / DGUEP", marzo: "", abril: "", mayo: "4-25", junio: "", julio: "", agosto: "" },
  { id: "18", actividad: "Envío de formatos de descarga y/o comisiones académicas o institucionales a la DGRH.", 
    proceso: "Formatos y anexos (Firma electrónica)", responsable: "DGAA / DGUEP / DGRI / DGI / DGRH", marzo: "", abril: "6", mayo: "25", junio: "", julio: "", agosto: "" },
  { id: "19", actividad: "Emisión y validación de EE para convocar.", 
    proceso: "Ver calendario", responsable: "DGAA / DGUEP / DGRI / DGI / DGRH", marzo: "", abril: "", mayo: "14-20", junio: "", julio: "", agosto: "" },
  { id: "20", actividad: "Publicación de Convocatoria de EE por Programa Educativo con oferta autorizada.", 
    proceso: "SYRCONI - SYRCONV - SYRCONB", responsable: "DGAA / DGUEP / DGRI / DGI / DGRH", marzo: "", abril: "", mayo: "27", junio: "", julio: "", agosto: "" },
  { id: "21", actividad: "Tercera sesión de tutorías (orientación para la IL).", 
    proceso: "", responsable: "DGDAIE / EA", marzo: "", abril: "", mayo: "16-23", junio: "", julio: "", agosto: "" },
  { id: "22", actividad: "Preparación de la inscripción en línea.", 
    proceso: "Ver calendario IL", responsable: "DGAE / SIIU / EA", marzo: "", abril: "", mayo: "12-29", junio: "", julio: "", agosto: "" },
  { id: "23", actividad: "Inscripción en línea por los estudiantes.", 
    proceso: "Portal Estudiantes", responsable: "DGAE / SIIU / EA", marzo: "", abril: "", mayo: "", junio: "1-3", julio: "", agosto: "" },
  { id: "24", actividad: "Análisis de cierres y aperturas con calificaciones de ordinarios.", 
    proceso: "", responsable: "DGAE / SIIU / EA", marzo: "", abril: "", mayo: "", junio: "30", julio: "6", agosto: "" },
  { id: "25", actividad: "Notificación a la SA del listado de plazas vacantes de tiempo completo y medio tiempo con disponibilidad presupuestal.", 
    proceso: "", responsable: "SAF", marzo: "", abril: "", mayo: "", junio: "", julio: "3-9", agosto: "" },
  { id: "26", actividad: "Solicitud de ocupación temporal de plazas vacantes de tiempo completo y medio tiempo a la Secretaría de Administración y Finanzas.", 
    proceso: "", responsable: "DGAA / DGUEP / DGRI / DGI / DGDC / DAFBG", marzo: "", abril: "", mayo: "", junio: "25", julio: "3", agosto: "" },
  { id: "27", actividad: "Generar el reporte de cargas académicas por organización para el proceso de revisión de cargas académicas a partir de que se autoriza el PE.", 
    proceso: "", responsable: "EA / DGAA / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "28", actividad: "Fecha límite de licencias con goce y sin goce de sueldo.", 
    proceso: "", responsable: "DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "9", agosto: "" },
  { id: "29", actividad: "Proceso de revisión de cargas académicas.", 
    proceso: "Ver calendario Cargas Académicas", responsable: "DGRH", marzo: "", abril: "", mayo: "11-27", junio: "", julio: "", agosto: "" },
  { id: "30", actividad: "Publicación de resultados de la Convocatoria de EE vacantes (subir las publicaciones de resultados en el portal institucional de las entidades convocadas). SEA y Escolarizado", 
    proceso: "Portal Institucional de la EA ", responsable: "EA / DGAA ", marzo: "", abril: "", mayo: "", junio: "", julio: "6", agosto: "" },
  { id: "31", actividad: "Bajas en ventanilla de EE.", 
    proceso: "SWPBAJA - SFAREGS", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "17-21" },
  { id: "32", actividad: "Análisis de cierres con calificaciones y bajas.", 
    proceso: "SWPBAJA - SFAREGS", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "24-25" },
  { id: "33", actividad: "Autorización de las DGAA el cierre de EE.", 
    proceso: "SWPBAJA - SFAREGS", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "24-25" },
  { id: "34", actividad: "La DGRF asigna o configura en subsistema la apertura de EE.", 
    proceso: "SWPBAJA - SFAREGS", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "24-25" },
  { id: "35", actividad: "Actualización de la carga académica con la apertura y cierre de EE.", 
    proceso: "SWPBAJA - SFAREGS", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "24-28" },
  { id: "36", actividad: "Inscripción a EE con lugares disponibles.", 
    proceso: "SWPBAJA - SFAREGS", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "26-28" },
  { id: "37", actividad: "Inscripción Posgrado.", 
    proceso: "SWPBAJA - SFAREGS", responsable: "DGAE", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "3-7 y 10-14" },
  { id: "38", actividad: "Envío de solicitudes de contratación de personal de las EE convocadas sin inconformidad o, en su caso, al siguiente día hábil de haberse resuelto la inconformidad (con los documentos de resolución) y de acuerdo al calendario de recepción de documentos para el trámite de pago de la Dirección de Personal 2026.", 
    proceso: "", responsable: "DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "3-14" },
  { id: "39", actividad: "Fecha límite de envío de la Oferta impartida en el periodo Intersemestral de Verano 2025.", 
    proceso: "Formato", responsable: "DGRH / EA / DGAA", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "28" },
  { id: "40", actividad: "Inicio de publicación de avisos de EE vacantes para personal académico interino.", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "22", julio: "", agosto: "" },
  { id: "41", actividad: "Inicio de clases Licenciatura/Posgrado.", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "17" },
  { id: "42", actividad: "Inicio de clases Sistema de Enseñanza Abierta (SEA).", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "22" },
  { id: "43", actividad: "Contratación del personal académico de EE convocadas (Escolarizado/SEA).", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "17 y 22" },
  { id: "44", actividad: "Envío de solicitudes de contratación de personal de las EE asigadas por CT al subsistema de RH.", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "15", julio: " ", agosto: "30" },
  { id: "45", actividad: "Contratación de personal no docente, a partir del inicio de labores (a solicitud de las necesidades de la entidad académica).", 
    proceso: "", responsable: "EA / DGAA / DGRF / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "" },
  { id: "46", actividad: "Registrar y documentar los horarios de la plantilla del Personal Académico docente y no docente.", 
    proceso: "", responsable: "EA / DGUEP / DGRH", marzo: "", abril: "", mayo: "", junio: "", julio: "", agosto: "21" }  
];


const ILINEA = [
  { id: "1", actividad: "Envío de programas educativos que realizarán IL a la DI.", 
    proceso: "", responsable: "DGAE", fechaTexto: "19 de marzo", fecha: "2026-03-19" },
  { id: "2", actividad: "Validación de PbR y cuotas pro-mejoras.", 
    proceso: "", responsable: "DI", fechaTexto: "23 de marzo al 17 de abril", fecha: "2026-04-17"},
  { id: "3", actividad: "Carga de MPA a SIIU", 
    proceso: "", responsable: "DGAE / DSIA", fechaTexto: "12 y 13 de mayo", fecha: "2026-05-13"},
  { id: "4", actividad: "Generación de archivo de oferta académica", 
    proceso: "SWASEIL", responsable: "EA", fechaTexto: "14 al 18 de mayo", fecha: "2026-05-18"},
  { id: "5", actividad: " Configuración de requisitos específicos", 
    proceso: "SWAREQE", responsable: "EA", fechaTexto: "14 al 18 de mayo", fecha: "2026-05-18"},
  { id: "6", actividad: "Ejecución de proceso de asignación de clase de acuerdo con avance crediticio del alumno", 
    proceso: "SWACLAV", responsable: "EA", fechaTexto: "14 al 18 de mayo", fecha: "2026-05-18"},
  { id: "7", actividad: "Ejecución de datos de validación", 
    proceso: "SWPVAIL", responsable: "DGAE", fechaTexto: "14 al 20 de mayo", fecha: "2026-05-20"},
  { id: "8", actividad: "Configuración de tabulador para generación de líneas de captura", 
    proceso: "", responsable: "DI", fechaTexto: "19 de mayo", fecha: "2026-05-19"},
  { id: "9", actividad: "Cancelación de EE del horario sugerido de alumnos", 
    proceso: "", responsable: "DSIA / DGAE", fechaTexto: "19 de mayo", fecha: "2026-05-19"},
  { id: "10", actividad: "Ejecución de proceso para asignación de bloque de los PE que usan bloques", 
    proceso: "SWPABLK", responsable: "DGAE", fechaTexto: "19 de mayo", fecha: "2026-05-19"},
  { id: "11", actividad: "Validación de bloques", 
    proceso: "", responsable: "DGAE", fechaTexto: "19 al 21 de mayo", fecha: "2026-05-21"},
  { id: "12", actividad: "Generación de tabla de historia académica y cuestionario IL", 
    proceso: "SWPTAIN - SWPTCIL", responsable: "DGAE", fechaTexto: "19 al 21 de mayo", fecha: "2026-05-21"},
  { id: "13", actividad: "Configuración de textos del portal", 
    proceso: "SWAREGE", responsable: "DGAE", fechaTexto: "19 al 21 de mayo", fecha: "2026-05-21"},
  { id: "14", actividad: "Ejecución de sorteo", 
    proceso: "", responsable: "DGAE", fechaTexto: "21 de mayo", fecha: "2026-05-21"},
  { id: "15", actividad: "Inicio de carga de datos para aplicación", 
    proceso: "", responsable: "DSIA / SIIU / DGAE", fechaTexto: "22 de mayo", fecha: "2026-05-22"},
  { id: "16", actividad: "Validación de aplicación", 
    proceso: "", responsable: "DSIA / SIIU / DGAE", fechaTexto: "25 al 28 de mayo", fecha: "2026-05-28"},
  { id: "17", actividad: "Validación de oferta en el portal", 
    proceso: "", responsable: "EA", fechaTexto: "27 y 28 de mayo", fecha: "2026-05-28"},
  { id: "18", actividad: "Publicación de sorteo y oferta", 
    proceso: "", responsable: "DSIA / SIIU / DGAE", fechaTexto: "27 de mayo", fecha: "2026-05-27"},
  { id: "19", actividad: "Ejecución de SWPTAIN y SWPCLAV", 
    proceso: "SWPTAIN - SWPCLAV", responsable: "DGAE", fechaTexto: "28 de mayo", fecha: "2026-05-28"},
  { id: "20", actividad: "Carga definitiva de datos (historia, causas y condiciones)", 
    proceso: "", responsable: "DSIA / SIIU / DGAE", fechaTexto: "29 de mayo", fecha: "2026-05-29"},
  { id: "21", actividad: "Inscripción en línea", 
    proceso: "", responsable: "Alumnos", fechaTexto: "1 al 3 de junio", fecha: "2026-06-03"},
  { id: "22", actividad: "Inscripción en línea extemporánea", 
    proceso: "", responsable: "Alumnos", fechaTexto: "4 de junio", fecha: "2026-06-04"},
  { id: "23", actividad: "Inscripción en línea a lugares disponibles", 
    proceso: "", responsable: "Alumnos", fechaTexto: "5 de junio", fecha: "2026-06-05"},
  { id: "24", actividad: "Carga de información de inscripción de SQL a SIIU", 
    proceso: "", responsable: "DSIA", fechaTexto: "2 de julio", fecha: "2026-07-02"},
  { id: "25", actividad: "Cancelación de EE por escolaridad o condición del alumno (posterior a la ejecución de SWPCLAV)", 
    proceso: "", responsable: "DSIA / SIIU / DGAE", fechaTexto: "6 de agosto", fecha: "2026-08-06"},
  { id: "26", actividad: "Consulta de horario final y pago de inscripción", 
    proceso: "", responsable: "Alumnos", fechaTexto: "10 al 14 de agosto", fecha: "2026-08-14"}
];


const CONVOCATORIAS = [
  { titulo: "Ejecución Convocatorias Previas", fechaTexto: "19 de mayo", fecha: "2026-05-19" },
  { titulo: "Ejecución Convocatorias Definitivas", fechaTexto: "20 de mayo", fecha: "2026-05-20" },
  { titulo: "Emisión (Publicación)", fechaTexto: "27 de mayo", fecha: "2026-05-27" },
  { titulo: "Recepción Documentos", fechaTexto: "15 al 17 de junio", fecha: "2026-06-17" },
  { titulo: "Examen de Oposición", fechaTexto: "25 de junio al 1 de julio", fecha: "2026-07-01" },
  { titulo: "Publicación de Resultados", fechaTexto: "6 de julio", fecha: "2026-07-06" }
];


const CARACAD = [
  { titulo: "Proceso de revisión de cargas académicas", fechaTexto: "11 al 27 de mayo", fecha: "2026-05-27" },
  { titulo: "Solicitud de apoyo a Vicerrectorías para revisión de cargas académicas", fechaTexto: "11 de mayo", fecha: "2026-05-11" },
  { titulo: "Envío de reporte de cargas académicas y horarios de la revisión de cargas académicas al Sindicato Estatal de Personal Académico de la Universidad Veracruzana (FESAPAUV)", 
    fechaTexto: "12 al 18 de mayo", fecha: "2026-05-18" },
  { titulo: "Revisión de cargas académicas en las regiones", fechaTexto: "19 al 27 de mayo", fecha: "2026-05-27" },
  { titulo: "Región Poza Rica-Tuxpan", fechaTexto: "19 de mayo", fecha: "2026-05-19" },
  { titulo: "Región Veracruz", fechaTexto: "20 de mayo", fecha: "2026-05-20" },
  { titulo: "Región Orizaba-Córdoba", fechaTexto: "21 de mayo", fecha: "2026-05-21" },
  { titulo: "Región Coatzacoalcos-Minatitlán", fechaTexto: "22 de mayo", fecha: "2026-05-22" },
  { titulo: "Región Xalapa", fechaTexto: "25 al 27 de mayo", fecha: "2026-05-27" }
];

const CARACADDP = [
  { titulo: "Proceso de revisión de cargas académicas", fechaTexto: "18 de mayo al 5 de junio", fecha: "2026-06-05" },
  { titulo: "Solicitud de apoyo a Vicerrectorías para revisión de cargas académicas", fechaTexto: "18 de mayo", fecha: "2026-05-18" },
  { titulo: "Envío de reporte de cargas académicas y horarios de la revisión de cargas académicas al Sindicato Estatal de Personal Académico de la Universidad Veracruzana (FESAPAUV)", 
    fechaTexto: "18 al 22 de mayo", fecha: "2026-05-22" },
  { titulo: "Revisión de cargas académicas en las regiones", fechaTexto: "26 de mayo al 3 de junio", fecha: "2026-06-03" },
  { titulo: "Región Poza Rica-Tuxpan", fechaTexto: "29 de mayo", fecha: "2026-05-29" },
  { titulo: "Región Veracruz", fechaTexto: "28 de mayo", fecha: "2026-05-28" },
  { titulo: "Región Orizaba-Córdoba", fechaTexto: "27 de mayo", fecha: "2026-05-27" },
  { titulo: "Región Coatzacoalcos-Minatitlán", fechaTexto: "26 de mayo", fecha: "2026-05-26" },
  { titulo: "Región Xalapa", fechaTexto: "1 al 3 de junio", fecha: "2026-06-03" }
];